### ISSUE TITLE
请问邀请注册之后会怎么发ETH?

### ISSUE THREAD

**Issue by leonliu1995** [xiaochao/CatchFish#1]
试了一下代码，可以用，但是邀请了之后没有发现有鱼啊？？
想问一下你的有么？

**Comment by xiaochao** [comment]
![image](https://user-images.githubusercontent.com/1953662/35445690-5d666336-02ed-11e8-9ebc-f7034ed7f090.png)
ETH是等系统正式上线，交易鱼获得
